/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compac.vista.principal;

import compac.clases.controlador.UsuarioImpl;
import compac.clases.principales.Conectar;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Tafur
 */
public class Ini_Presentacion extends javax.swing.JFrame {

    UsuarioImpl controlador = new UsuarioImpl(); //llamamos al mentenimiento general del objeto

    public Ini_Presentacion() {
//        JFrame.setDefaultLookAndFeelDecorated(true);
//        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeSkin");
        initComponents();
        new Thread(new Tiempo()).start();
        this.setLocationRelativeTo(null);
        ///////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////
        //////////////////////////////////ICONO DEL FRAEM
        setIconImage(new ImageIcon(getClass().getResource("/compac/icono/general/logos.png")).getImage());
        ///////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.setForeground(new java.awt.Color(65, 158, 247));
        barra.setAutoscrolls(true);
        barra.setBorderPainted(false);
        barra.setRequestFocusEnabled(false);
        barra.setStringPainted(true);
        barra.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(26, 106, 146));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("Inicializando");
        jPanel2.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 500, 31));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compac/vista/principal/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 130));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public class Tiempo implements Runnable {

        @Override
        public void run() {
            try {
                barra.repaint();

                for (int cont = 0; cont < 100; cont++) {
                    Thread.sleep(5);    // LA VELOCIDAD DE TU BARRA DE PROGRESO
                    barra.setValue(cont);
                    if (cont == 5) {
                        lblTexto.setText("Inicializando Archivos");
                    }
                    if (cont == 10) {     //CUANDO CONT LLEGUE A 20% QUE TE MUESTRE ESTE MENSAJE
                        lblTexto.setText("Inicializando Archivos.");
                    }
                    if (cont == 15) {
                        lblTexto.setText("Inicializando Archivos..");
                    }
                    if (cont == 20) {
                        lblTexto.setText("Inicializando Archivos...");
                    }
                    if (cont == 30) {
                        lblTexto.setText("Inicializando Base de Datos");
                    }
                    if (cont == 38) {
                        lblTexto.setText("Inicializando Base de Datos.");
                    }
                    if (cont == 46) {
                        lblTexto.setText("Inicializando Base de Datos..");
                    }
                    if (cont == 54) {
                        lblTexto.setText("Inicializando Base de Datos...");
                    }
                    if (cont == 65) {
                        lblTexto.setText("Inicializando Plugins");
                    }
                    if (cont == 70) {
                        lblTexto.setText("Inicializando Plugins.");
                    }
                    if (cont == 75) {
                        lblTexto.setText("Inicializando Plugins..");
                    }
                    if (cont == 80) {
                        lblTexto.setText("Inicializando Plugins...");
                    }
                    if (cont == 85) {
                        lblTexto.setText("Inicializando Librerias.");
                    }
                    if (cont == 85) {
                        lblTexto.setText("Inicializando Librerias..");
                    }
                    if (cont == 90) {
                        lblTexto.setText("Inicializando Librerias...");
                    }
                    if (cont == 93) {
                        lblTexto.setText("Preparando Para iniciar");
                    }
                    if (cont == 96) {
                        lblTexto.setText("Carga Completa");
                    }
                    if (cont == 99) {

                        Conectar conectar = new Conectar();
                        Connection con = conectar.getConexion();
                        if (con != null) {
                            int idUsuario = controlador.obtenerEntero("Select max(id_usuario) from usuario ");
                            int idSede = controlador.obtenerEntero("Select max(id_sede) from sede ");
                            Frm_Login logeo = new Frm_Login(idUsuario, idSede);
//                        logeo.setSize(536, 239);
                            logeo.setVisible(true);
                            logeo.setLocationRelativeTo(null);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al procesar la carga de componentes", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                            int opcion = JOptionPane.showConfirmDialog(null, "Desea conectar a un terminal?", "Mensaje", JOptionPane.OK_CANCEL_OPTION);
                            if (opcion == JOptionPane.OK_OPTION) {
                                Servidor serv = new Servidor();
                                serv.setLocationRelativeTo(null);
                                serv.setVisible(true);
                                dispose();
                            } else {
                                dispose();
                            }
                        }

                    }
                }

            } catch (Exception ex) {  //EL CATCH ES POR SI TU PROGRAMA TIENE UN ERROR
                System.err.println("error en : " + ex.getLocalizedMessage());

                JOptionPane.showMessageDialog(null, "Error al procesar la carga de componentes", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

                JOptionPane.showMessageDialog(null, "Error al procesar la carga de componentes", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                int opcion = JOptionPane.showConfirmDialog(null, "Desea conectar a un terminal?", "Mensaje", JOptionPane.OK_CANCEL_OPTION);
                if (opcion == JOptionPane.OK_OPTION) {
                    Servidor serv = new Servidor();
                    serv.setLocationRelativeTo(null);
                    serv.setVisible(true);
                    dispose();
                } else {
                    dispose();
                }
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ini_Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ini_Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ini_Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ini_Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ini_Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
